### PR TITLE
✨ Laravel 7 Support

### PR DESCRIPTION
**Pull request by irazasyed**

### CODE REVIEW

**Comment by nerg4l** [comment]
Could you update travis as well?

**Comment by irazasyed** [comment]
Updated but I think it might fail since Laravel 7 requires PHP Unit 8.4.

**Comment by irazasyed** [comment]
So we need to exclude Laravel 7 in PHP 7.1. Should I also update it to PHPUnit 8.4?

**Comment by axlon** [comment]
Thank you for your contribution, TravisCI seems to throw an error on PHP 7.4 currently, I'll take a look at it soon and notify you when its merged/tagged.

**Comment by irazasyed** [comment]
Yeah I noticed. 

Sounds good. Thanks!

**Comment by axlon** [comment]
@irazasyed 0.4.0 has been tagged!

**Comment by irazasyed** [comment]
Awesome! Thanks @axlon :)

**Pull request merged**
